"""Add features, feedback tables

Revision ID: 18b9a7ca6696
Revises: 8c47264490dd
Create Date: 2024-05-22 14:35:15.645336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b9a7ca6696'
down_revision = '8c47264490dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('hrs_slept', sa.Integer(), nullable=False),
    sa.Column('sleep_quality', sa.String(), nullable=False),
    sa.Column('food_taken', sa.String(), nullable=False),
    sa.Column('food_amount', sa.String(), nullable=False),
    sa.Column('drink', sa.String(), nullable=False),
    sa.Column('temperatures', sa.String(), nullable=False),
    sa.Column('exercise', sa.String(), nullable=False),
    sa.Column('medication', sa.String(), nullable=False),
    sa.Column('visit_restroom', sa.String(), nullable=False),
    sa.Column('times_visited', sa.Integer(), nullable=False),
    sa.Column('caregiver', sa.String(length=30), nullable=True),
    sa.Column('child_name', sa.String(length=50), nullable=True),
    sa.Column('predicted', sa.String(length=10), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed', sa.Text(), nullable=False),
    sa.Column('features_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['features_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('features')
    # ### end Alembic commands ###
