"""Modify column types

Revision ID: 24df0bbe4224
Revises: cbd6be73df6e
Create Date: 2024-05-22 14:50:56.751708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24df0bbe4224'
down_revision = 'cbd6be73df6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.alter_column('predicted',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('probability',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('probability',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('predicted',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
