"""Modify column types

Revision ID: cbd6be73df6e
Revises: 18b9a7ca6696
Create Date: 2024-05-22 14:48:35.857661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd6be73df6e'
down_revision = '18b9a7ca6696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.alter_column('temperatures',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.alter_column('temperatures',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
